# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodebuildMultirunner < Formula
  desc ""
  homepage ""
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koh-sh/codebuild-multirunner/releases/download/v0.3.0/codebuild-multirunner_Darwin_x86_64.tar.gz"
      sha256 "ef673826474f96ca5c492449e4ae3e3fcfe253540fdf2d41b9445fddbfeb36d7"

      def install
        bin.install "codebuild-multirunner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koh-sh/codebuild-multirunner/releases/download/v0.3.0/codebuild-multirunner_Darwin_arm64.tar.gz"
      sha256 "a23d1656e18d65c09a45bf4be4fa856e4e19aba0e4d9212c46ac237ed96256a8"

      def install
        bin.install "codebuild-multirunner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/koh-sh/codebuild-multirunner/releases/download/v0.3.0/codebuild-multirunner_Linux_x86_64.tar.gz"
      sha256 "73ae26a51e596ed69c10c8432fbfe0f250dd9c3577ac81f956c240ba5f9f765b"

      def install
        bin.install "codebuild-multirunner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koh-sh/codebuild-multirunner/releases/download/v0.3.0/codebuild-multirunner_Linux_arm64.tar.gz"
      sha256 "1f2096d205b7daeeaf530e46b1a5cf8530ddaefb78011c01058a6cc9a7727147"

      def install
        bin.install "codebuild-multirunner"
      end
    end
  end
end
