# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhaTimegraph < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/koh-sh/gha-timegraph/releases/download/v0.0.1/gha-timegraph_Darwin_arm64.tar.gz"
      sha256 "72a183b6ada287b815f129d22f8dca4c91434fd1357e97f9a0699bc38f6f2f0d"

      def install
        bin.install "gha-timegraph"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koh-sh/gha-timegraph/releases/download/v0.0.1/gha-timegraph_Darwin_x86_64.tar.gz"
      sha256 "ae004dea130776071d9eb2a2b7e4cd8200aa2837100d63d1c49bc8bb8a70b3ee"

      def install
        bin.install "gha-timegraph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koh-sh/gha-timegraph/releases/download/v0.0.1/gha-timegraph_Linux_arm64.tar.gz"
      sha256 "9c5560951b258c81ddbf3ac10b1f0257fa3448f71f73b1fed82368f601f646b9"

      def install
        bin.install "gha-timegraph"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/koh-sh/gha-timegraph/releases/download/v0.0.1/gha-timegraph_Linux_x86_64.tar.gz"
      sha256 "23ff077816d0f4363c0b978378842c908b0e6ee76fcd24224ca485d7e9a40270"

      def install
        bin.install "gha-timegraph"
      end
    end
  end
end
