# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhaTimegraph < Formula
  desc ""
  homepage ""
  version "0.2.2"

  on_macos do
    on_intel do
      url "https://github.com/koh-sh/gha-timegraph/releases/download/v0.2.2/gha-timegraph_Darwin_x86_64.tar.gz"
      sha256 "47489c33cd0f226ff8372605a33944bdcfeb098c2b2ce85c975b464a0d3d8b40"

      def install
        bin.install "gha-timegraph"
      end
    end
    on_arm do
      url "https://github.com/koh-sh/gha-timegraph/releases/download/v0.2.2/gha-timegraph_Darwin_arm64.tar.gz"
      sha256 "f40c2047ea58f604ccfb8023dbd83e3199da119f3f2b478cffe68d61994ca49d"

      def install
        bin.install "gha-timegraph"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/koh-sh/gha-timegraph/releases/download/v0.2.2/gha-timegraph_Linux_x86_64.tar.gz"
        sha256 "0a4755a267481506507e018f9bcb17603fea2624bee7a66af6838254469a2c63"

        def install
          bin.install "gha-timegraph"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/koh-sh/gha-timegraph/releases/download/v0.2.2/gha-timegraph_Linux_arm64.tar.gz"
        sha256 "73a54655ddc81a5547b70b41826661fc700addec2a86231491958b066390fbf5"

        def install
          bin.install "gha-timegraph"
        end
      end
    end
  end
end
