# This file was generated by GoReleaser. DO NOT EDIT.
cask "apcdeploy" do
  name "apcdeploy"
  desc ""
  homepage ""
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apcdeploy"

  on_macos do
    on_intel do
      url "https://github.com/koh-sh/apcdeploy/releases/download/v#{version}/apcdeploy_Darwin_x86_64.tar.gz"
      sha256 "e40ae97b5af88af75447422f0d80749eb3050c59014fcc7500fad841c8bd217d"
    end
    on_arm do
      url "https://github.com/koh-sh/apcdeploy/releases/download/v#{version}/apcdeploy_Darwin_arm64.tar.gz"
      sha256 "c695655dd8d108902218d0ba54932c3668df6aa6e61dbbdbecbb53426441d138"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/koh-sh/apcdeploy/releases/download/v#{version}/apcdeploy_Linux_x86_64.tar.gz"
      sha256 "687055eebaf7d51e255e668356b0ddb1bba8e4c3fc90a20bb38c390ec7cb95d5"
    end
    on_arm do
      url "https://github.com/koh-sh/apcdeploy/releases/download/v#{version}/apcdeploy_Linux_arm64.tar.gz"
      sha256 "24d85a77e121e62ca398fbe0590bc892c57c57d37673ba01f20d61f81596a7d3"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/apcdeploy"]
    end
  end

  # No zap stanza required
end
