# This file was generated by GoReleaser. DO NOT EDIT.
cask "apcdeploy" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "86140ceda2ab63969b176312c5524279e5c79b35615c8c54d33f4167600ae66e"
      url "https://github.com/koh-sh/apcdeploy/releases/download/v#{version}/apcdeploy_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "85e0aecf85f338284f2b446d90d584ff0733ca70801b8ea718d908742f05d3f0"
      url "https://github.com/koh-sh/apcdeploy/releases/download/v#{version}/apcdeploy_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1e7caa1f1d116fe8683bc086b9c2174a04b9da9555de268a4211f2f890666cbb"
      url "https://github.com/koh-sh/apcdeploy/releases/download/v#{version}/apcdeploy_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a06ad5cfdfd4270b3a325fd4ae9b5b0a789e25b6480313c00655d71017397535"
      url "https://github.com/koh-sh/apcdeploy/releases/download/v#{version}/apcdeploy_Linux_arm64.tar.gz"
    end
  end

  name "apcdeploy"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apcdeploy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/apcdeploy"]
    end
  end

  # No zap stanza required

end
