# This file was generated by GoReleaser. DO NOT EDIT.
cask "apcdeploy" do
  name "apcdeploy"
  desc ""
  homepage ""
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apcdeploy"

  on_macos do
    on_intel do
      url "https://github.com/koh-sh/apcdeploy/releases/download/v#{version}/apcdeploy_Darwin_x86_64.tar.gz"
      sha256 "2ef99e73dddfeb5b3d721e07cf19085401f65f08c97870ff0ea4fc98278866d1"
    end
    on_arm do
      url "https://github.com/koh-sh/apcdeploy/releases/download/v#{version}/apcdeploy_Darwin_arm64.tar.gz"
      sha256 "1155701f88053729d30d0592a2c4aa1ac4022529d5c99decc0ed19051312bd16"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/koh-sh/apcdeploy/releases/download/v#{version}/apcdeploy_Linux_x86_64.tar.gz"
      sha256 "46e8fca8c3201a6aa70a3ed1e84ab0a9f2cdf45c5c8f3606ca9f65b3b9448a2f"
    end
    on_arm do
      url "https://github.com/koh-sh/apcdeploy/releases/download/v#{version}/apcdeploy_Linux_arm64.tar.gz"
      sha256 "21ff79a8d10e1dd6fa21602d5846a190935992709621684a4d487d1e742602b0"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/apcdeploy"]
    end
  end

  # No zap stanza required
end
