# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccnewline" do
  desc ""
  homepage ""
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccnewline"

  on_macos do
    on_intel do
      url "https://github.com/koh-sh/ccnewline/releases/download/v0.0.2/ccnewline_Darwin_x86_64.tar.gz"
      sha256 "5fd6a39dd669f5012389588fde141587ca1dd6452f3edeb35cb92413cef31147"
    end
    on_arm do
      url "https://github.com/koh-sh/ccnewline/releases/download/v0.0.2/ccnewline_Darwin_arm64.tar.gz"
      sha256 "b49a8286cac9d05fe7089a186737f3bd97e4745644ecd5a998e6a2b1335378ce"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/koh-sh/ccnewline/releases/download/v0.0.2/ccnewline_Linux_x86_64.tar.gz"
      sha256 "7f634fcf0e9b59ec78f5facd821b314e3dcf1599354061b5cc72bc95ae40fc21"
    end
    on_arm do
      url "https://github.com/koh-sh/ccnewline/releases/download/v0.0.2/ccnewline_Linux_arm64.tar.gz"
      sha256 "2b794a11e6e1c8cc78fc4350efe249eb66ffda0a29720b560b81eccd90625564"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccnewline"]
    end
  end

  # No zap stanza required
end
