# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccnewline" do
  desc ""
  homepage ""
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccnewline"

  on_macos do
    on_intel do
      url "https://github.com/koh-sh/ccnewline/releases/download/v0.0.1/ccnewline_Darwin_x86_64.tar.gz"
      sha256 "3f46dcf787cf47b48885cea94fce8f21a817937a125d2adac6fd162c6f292699"
    end
    on_arm do
      url "https://github.com/koh-sh/ccnewline/releases/download/v0.0.1/ccnewline_Darwin_arm64.tar.gz"
      sha256 "ac175ad201a4ab41e5948ab2188f3bb9c9d00cdfc35ac923e6ea2fd293d6e1e8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/koh-sh/ccnewline/releases/download/v0.0.1/ccnewline_Linux_x86_64.tar.gz"
      sha256 "01ba1522dd186448b69008fa43b9bf6cd52de56a7c18b4ec34db5925385a1950"
    end
    on_arm do
      url "https://github.com/koh-sh/ccnewline/releases/download/v0.0.1/ccnewline_Linux_arm64.tar.gz"
      sha256 "01b2f9443625cc34554b517d4b4c6c88e545ba0bdfae2c0814b84fa28a2ab95f"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccnewline"]
    end
  end

  # No zap stanza required
end
