# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccnewline" do
  desc ""
  homepage ""
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccnewline"

  on_macos do
    on_intel do
      url "https://github.com/koh-sh/ccnewline/releases/download/v0.1.0/ccnewline_Darwin_x86_64.tar.gz"
      sha256 "eac9ce3a6583281b14be3b6b266f707903324f5083d712c22aa6e9c7b81f3f15"
    end
    on_arm do
      url "https://github.com/koh-sh/ccnewline/releases/download/v0.1.0/ccnewline_Darwin_arm64.tar.gz"
      sha256 "7f0f564b74571f1e8ec55744f0f515fdbee9727dbf1949457f959f481fbc128c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/koh-sh/ccnewline/releases/download/v0.1.0/ccnewline_Linux_x86_64.tar.gz"
      sha256 "2284793feb38aa47f71ab3104f0d63e1fdb869c55a36d0547ce59cfb15925cf6"
    end
    on_arm do
      url "https://github.com/koh-sh/ccnewline/releases/download/v0.1.0/ccnewline_Linux_arm64.tar.gz"
      sha256 "1807728f8e32300c3948d0ae5aad0ef66cd7e3aca8c3a0ec3e5cdf96ba324225"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccnewline"]
    end
  end

  # No zap stanza required
end
