# This file was generated by GoReleaser. DO NOT EDIT.
cask "codebuild-multirunner" do
  desc ""
  homepage ""
  version "0.11.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codebuild-multirunner"

  on_macos do
    on_intel do
      url "https://github.com/koh-sh/codebuild-multirunner/releases/download/v0.11.2/codebuild-multirunner_Darwin_x86_64.tar.gz"
      sha256 "f20bd201ea0fac9b47715eefdb0e83858070f321a6a5cad56d2371346a9cafcd"
    end
    on_arm do
      url "https://github.com/koh-sh/codebuild-multirunner/releases/download/v0.11.2/codebuild-multirunner_Darwin_arm64.tar.gz"
      sha256 "b3a5c96bf5e82e7cab02df7e0b49978c95500e314f4a5f568e60bf73fe3791b8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/koh-sh/codebuild-multirunner/releases/download/v0.11.2/codebuild-multirunner_Linux_x86_64.tar.gz"
      sha256 "fe0ec7c0b659156fa2bd26e135eff2d7bdf64bf8b7371a60aa32d25a0451c752"
    end
    on_arm do
      url "https://github.com/koh-sh/codebuild-multirunner/releases/download/v0.11.2/codebuild-multirunner_Linux_arm64.tar.gz"
      sha256 "0359cff06e1df1cf837244762df6ab4e70b9ab702f0eca70dc337a84b38e14d9"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/codebuild-multirunner"]
    end
  end

  # No zap stanza required
end
