# This file was generated by GoReleaser. DO NOT EDIT.
cask "codebuild-multirunner" do
  name "codebuild-multirunner"
  desc ""
  homepage ""
  version "0.14.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codebuild-multirunner"

  on_macos do
    on_intel do
      url "https://github.com/koh-sh/codebuild-multirunner/releases/download/v#{version}/codebuild-multirunner_Darwin_x86_64.tar.gz"
      sha256 "161ec649f2f9429b82a17df033493ff46bc12119e944d596b77fb8d23c6ee907"
    end
    on_arm do
      url "https://github.com/koh-sh/codebuild-multirunner/releases/download/v#{version}/codebuild-multirunner_Darwin_arm64.tar.gz"
      sha256 "110dca7e59bd2bc853b5eaf36c8b350f386a089b38e97554b3bbde7bc543b845"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/koh-sh/codebuild-multirunner/releases/download/v#{version}/codebuild-multirunner_Linux_x86_64.tar.gz"
      sha256 "a38212ef5e30264d6407238c4636a7f71ca274bb0890b3185e2a7dea1412ef10"
    end
    on_arm do
      url "https://github.com/koh-sh/codebuild-multirunner/releases/download/v#{version}/codebuild-multirunner_Linux_arm64.tar.gz"
      sha256 "7d471f3155b01afc139f5b05caba34b3828846909ce97dfb92034670584d3abf"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/codebuild-multirunner"]
    end
  end

  # No zap stanza required
end
