# This file was generated by GoReleaser. DO NOT EDIT.
cask "codebuild-multirunner" do
  desc ""
  homepage ""
  version "0.11.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codebuild-multirunner"

  on_macos do
    on_intel do
      url "https://github.com/koh-sh/codebuild-multirunner/releases/download/v0.11.0/codebuild-multirunner_Darwin_x86_64.tar.gz"
      sha256 "0f33ef425396767d4ee36bf99ff894cb54dc19a9340354927375ff3aaeb79e97"
    end
    on_arm do
      url "https://github.com/koh-sh/codebuild-multirunner/releases/download/v0.11.0/codebuild-multirunner_Darwin_arm64.tar.gz"
      sha256 "69b505739e130f82fe6d51934b88bb14819d085cded73b14c72a8aad58fcc517"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/koh-sh/codebuild-multirunner/releases/download/v0.11.0/codebuild-multirunner_Linux_x86_64.tar.gz"
      sha256 "dea9834e2290fd9e38bdc119f1a3e4a7beefddd99c844e2a1de45020bfa94c68"
    end
    on_arm do
      url "https://github.com/koh-sh/codebuild-multirunner/releases/download/v0.11.0/codebuild-multirunner_Linux_arm64.tar.gz"
      sha256 "857b63181e4b6f5923db1ae40aab8546cf3b2e082c23cac72132a78fd100c572"
    end
  end

  # No zap stanza required
end
